### ISSUE TITLE
[BUG]: media_ keys don't do anything

### ISSUE THREAD

**Issue by hobbesjaap** [streamdeck-linux-gui/streamdeck-linux-gui#101]
### In raising this issue I confirm that

- [X] I have fully completed the issue template
- [X] I have searched open and closed issues for duplicates
- [X] I have read the [Contribution Guidelines](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/contributing/contributing-guide/)
- [X] I have read the [Code of Conduct](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/contributing/code-of-conduct/)
- [X] I have read the [Documentation](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/)

### Describe the bug

I recently purchased a Stream Deck and am so happy this project exists. I'm running Manjaro Linux kernel 6.5 and installed streamdeck-ui via AUR. It's automatically installed version 3.1.0-1, which is great. Since Python 3 is running as a system install, using pip isn't an option for me so having an AUR package has been great.

That being said, maybe that's where my issue has come from? The software is running great, I'm able to configure the buttons, dimming, etc. The issue I have is that none of the  media_ keys do anything.

I run Wayland GNOME 45.

### Steps to reproduce the behavior

1. I've created custom buttons for mute, volume down and volume up.
2. I've assigned "Press Keys" with media_volume_mute, media_volume_down and media_volume_up
3. When pressing the keys on my Stream Deck, nothing happens.
4. I've tried using media_next, media_previous, media_play_pause as well. None of the media calls work.

### Expected behavior

I expected the media_keys to be recognised. They are recognised without any effort on my actual keyboard, but I have to use the Fn button on my keyboard, which is a hassle. Using the StreamDeck would be ideal.

### System Information

* OS: Manjaro Linux - Kernel 6.5.7-2-MANJARO
* Desktop environment: GNOME 45.0
* Python 3.11.5

### Stream Deck Version

Stream Deck Standard Original

**Comment by 4s3ti** [comment]
Is not just media keys. some features do not work on wayland due to lack of support on the upstream libraries.

**Comment by 4s3ti** [comment]
https://github.com/streamdeck-linux-gui/streamdeck-linux-gui/releases/tag/v4.1.0
