### ISSUE TITLE
[FEATURE]: Any way to disable tray icon?

### ISSUE THREAD

**Issue by Razer0123** [streamdeck-linux-gui/streamdeck-linux-gui#108]
### In raising this issue I confirm that

- [X] I have fully completed the issue template
- [X] I have searched open and closed issues for duplicates
- [X] I have read the [Contribution Guidelines](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/contributing/contributing-guide/)
- [X] I have read the [Code of Conduct](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/contributing/code-of-conduct/)
- [X] I have read the [Documentation](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/)

### Describe the bug

wanting to hide tray icon

### Steps to reproduce the behavior

starting the program

### Expected behavior

hidden tray icon

### System Information

fedora 39

**Comment by 4s3ti** [comment]
feature rquets should be done in Discussions.
