### ISSUE TITLE
[BUG]: streamdeck-ui crashing on launch

### ISSUE THREAD

**Issue by BinaryVigilante** [streamdeck-linux-gui/streamdeck-linux-gui#118]
### In raising this issue I confirm that

- [X] I have fully completed the issue template
- [X] I have searched open and closed issues for duplicates
- [X] I have read the [Contribution Guidelines](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/contributing/contributing-guide/)
- [X] I have read the [Code of Conduct](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/contributing/code-of-conduct/)
- [X] I have read the [Documentation](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/)

### Describe the bug

Hello,

I just upgraded streamdeck-ui to version 4.0.0-1 and are getting the following crash:
```
$ streamdeck
Traceback (most recent call last):
  File "/usr/bin/streamdeck", line 5, in <module>
    from streamdeck_ui.gui import start
  File "/usr/lib/python3.11/site-packages/streamdeck_ui/gui.py", line 45, in <module>
    from streamdeck_ui.modules.fonts import DEFAULT_FONT_FAMILY, FONTS_DICT, find_font_info
  File "/usr/lib/python3.11/site-packages/streamdeck_ui/modules/fonts.py", line 151, in <module>
    DEFAULT_FONT_FAMILY, DEFAULT_FONT_STYLE = find_font_info(DEFAULT_FONT)
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/streamdeck_ui/modules/fonts.py", line 147, in find_font_info
    return find_font_info(DEFAULT_FONT)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/streamdeck_ui/modules/fonts.py", line 147, in find_font_info
    return find_font_info(DEFAULT_FONT)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/streamdeck_ui/modules/fonts.py", line 147, in find_font_info
    return find_font_info(DEFAULT_FONT)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 979 more times]
  File "/usr/lib/python3.11/site-packages/streamdeck_ui/modules/fonts.py", line 143, in find_font_info
    for font_family, font_styles in FONTS_DICT.items():
                                    ^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded while calling a Python object
```

### Steps to reproduce the behavior

Install and launch streamdeck-ui.

### Expected behavior

I expected streamdeck-ui to launch.

### System Information

* Arch Linux
* Xfce4 as Desktop
* Python version is 3.11.5
* Kernel 6.1.61-1-lts

### Stream Deck Version

XL

**Comment by smarrk** [comment]
On Arch a workaround for this error is to install `ttf-roboto`
(Which is already shipped with the package but not found for unkown reason)

**Comment by smarrk** [comment]
I just realized, that I had a lot of  references to `/usr/share/fonts/TTF/Roboto-Regular.ttf` in my config file.
Changing this to `Roboto-Regular.ttf` removes the dependency to the external font and fixes the above error.

**Comment by Razer0123** [comment]
Having the same issue on Fedora, tried installing Roboto fonts but did not fix the issue

**Comment by Razer0123** [comment]
> I just realized, that I had a lot of references to `/usr/share/fonts/TTF/Roboto-Regular.ttf` in my config file. Changing this to `Roboto-Regular.ttf` removes the dependency to the external font and fixes the above error.

which config file?

**Comment by smarrk** [comment]
> > I just realized, that I had a lot of references to `/usr/share/fonts/TTF/Roboto-Regular.ttf` in my config file. Changing this to `Roboto-Regular.ttf` removes the dependency to the external font and fixes the above error.
> 
> which config file?

`~/.streamdeck_ui.json`

**Comment by Razer0123** [comment]
> > > I just realized, that I had a lot of references to `/usr/share/fonts/TTF/Roboto-Regular.ttf` in my config file. Changing this to `Roboto-Regular.ttf` removes the dependency to the external font and fixes the above error.
> > 
> > 
> > which config file?
> 
> `~/.streamdeck_ui.json`



> > > I just realized, that I had a lot of references to `/usr/share/fonts/TTF/Roboto-Regular.ttf` in my config file. Changing this to `Roboto-Regular.ttf` removes the dependency to the external font and fixes the above error.
> > 
> > 
> > which config file?
> 
> `~/.streamdeck_ui.json`

I have nothing inside that file referring to fonts, would you mind sharing yours so i can try using it?

**Comment by ajbucci** [comment]
> I just realized, that I had a lot of references to `/usr/share/fonts/TTF/Roboto-Regular.ttf` in my config file. Changing this to `Roboto-Regular.ttf` removes the dependency to the external font and fixes the above error.

I think this issue is unrelated. The source of the error ```DEFAULT_FONT_FAMILY, DEFAULT_FONT_STYLE = find_font_info(DEFAULT_FONT)``` _shouldn't_ depend on the config json.

@BinaryVigilante can you check if ```/usr/lib/python3.11/site-packages/streamdeck_ui/fonts/roboto/Roboto-Regular.ttf``` exists on your system?

**Comment by BinaryVigilante** [comment]
> @BinaryVigilante can you check if `/usr/lib/python3.11/site-packages/streamdeck_ui/fonts/roboto/Roboto-Regular.ttf` exists on your system?

I just checked, yeah they do exist.
![image](https://github.com/streamdeck-linux-gui/streamdeck-linux-gui/assets/24778415/80b19180-38d7-4499-bb43-469a2748aa6c)

**Comment by ajbucci** [comment]
@BinaryVigilante Are you still getting the error? Or did installing ttf-roboto "fix" it?

Are you comfortable adding ```print(os.path.join(FONTS_FALLBACK_PATH, DEFAULT_FONT))``` to line 10 in ```/usr/lib/python3.11/site-packages/streamdeck_ui/modules/fonts.py``` and then running ```streamdeck``` from your terminal and sharing the output here?

**Comment by teras** [comment]
I have the same error. After adding your comment I get this:

```
/usr/lib/python3.11/site-packages/streamdeck_ui/fonts/roboto/Roboto-Regular.ttf
Traceback (most recent call last):
  File "/usr/bin/streamdeck", line 5, in <module>
    from streamdeck_ui.gui import start
  File "/usr/lib/python3.11/site-packages/streamdeck_ui/gui.py", line 45, in <module>
    from streamdeck_ui.modules.fonts import DEFAULT_FONT_FAMILY, FONTS_DICT, find_font_info
  File "/usr/lib/python3.11/site-packages/streamdeck_ui/modules/fonts.py", line 152, in <module>
    DEFAULT_FONT_FAMILY, DEFAULT_FONT_STYLE = find_font_info(DEFAULT_FONT)
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/streamdeck_ui/modules/fonts.py", line 148, in find_font_info
    return find_font_info(DEFAULT_FONT)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/streamdeck_ui/modules/fonts.py", line 148, in find_font_info
    return find_font_info(DEFAULT_FONT)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/streamdeck_ui/modules/fonts.py", line 148, in find_font_info
    return find_font_info(DEFAULT_FONT)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 979 more times]
  File "/usr/lib/python3.11/site-packages/streamdeck_ui/modules/fonts.py", line 144, in find_font_info
    for font_family, font_styles in FONTS_DICT.items():
                                    ^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded while calling a Python object
```

The file `/usr/lib/python3.11/site-packages/streamdeck_ui/fonts/roboto/Roboto-Regular.ttf` exists in my system

**Comment by ajbucci** [comment]
> I have the same error. After adding your comment I get this:

@teras Do you already have roboto installed on your system? If yes, is the system font file not named Roboto-Regular.ttf? I think the recursion could be due to that if so. 

Can you try overwriting ```/usr/lib/python3.11/site-packages/streamdeck_ui/modules/fonts.py``` with this: 
https://raw.githubusercontent.com/ajbucci/streamdeck-linux-gui/default-font-fix/streamdeck_ui/modules/fonts.py 
(from: https://github.com/streamdeck-linux-gui/streamdeck-linux-gui/commit/e4c918ee41931ea8dd9cb080496752843b1c0026)

Let me know if that fixes it. Thanks!

**Comment by teras** [comment]
I'm on arch linux too and I have already installed ttf-roboto.
Also file `/usr/lib/python3.11/site-packages/streamdeck_ui/fonts/roboto/Roboto-Regular.ttf` is an actual ttf file.

The file that you proposed fixed the issue! 

```
ttf-roboto /usr/
ttf-roboto /usr/share/
ttf-roboto /usr/share/fonts/
ttf-roboto /usr/share/fonts/TTF/
ttf-roboto /usr/share/fonts/TTF/Roboto-Black.ttf
ttf-roboto /usr/share/fonts/TTF/Roboto-BlackItalic.ttf
ttf-roboto /usr/share/fonts/TTF/Roboto-Bold.ttf
ttf-roboto /usr/share/fonts/TTF/Roboto-BoldItalic.ttf
ttf-roboto /usr/share/fonts/TTF/Roboto-Italic.ttf
ttf-roboto /usr/share/fonts/TTF/Roboto-Light.ttf
ttf-roboto /usr/share/fonts/TTF/Roboto-LightItalic.ttf
ttf-roboto /usr/share/fonts/TTF/Roboto-Medium.ttf
ttf-roboto /usr/share/fonts/TTF/Roboto-MediumItalic.ttf
ttf-roboto /usr/share/fonts/TTF/Roboto-Regular.ttf
ttf-roboto /usr/share/fonts/TTF/Roboto-Thin.ttf
ttf-roboto /usr/share/fonts/TTF/Roboto-ThinItalic.ttf
ttf-roboto /usr/share/fonts/TTF/RobotoCondensed-Bold.ttf
ttf-roboto /usr/share/fonts/TTF/RobotoCondensed-BoldItalic.ttf
ttf-roboto /usr/share/fonts/TTF/RobotoCondensed-Italic.ttf
ttf-roboto /usr/share/fonts/TTF/RobotoCondensed-Light.ttf
ttf-roboto /usr/share/fonts/TTF/RobotoCondensed-LightItalic.ttf
ttf-roboto /usr/share/fonts/TTF/RobotoCondensed-Regular.ttf
```

**Comment by ajbucci** [comment]
> The file that you proposed fixed the issue! 
Glad it fixed it!

> ```
> ...
> ttf-roboto /usr/share/fonts/TTF/Roboto-Regular.ttf
> ...
> ttf-roboto /usr/share/fonts/TTF/RobotoCondensed-Regular.ttf
> ```
So your system's version of roboto regular shares the same filename as the packaged version... I wonder if RobotoCondensed-Regular.ttf is _also_ coming through as "family: roboto, style: regular" and overwriting the Roboto-Regular.ttf filename in the system font dictionary. 

I'll submit a PR with a fix soon.

**Comment by ajbucci** [comment]
@teras Although I'm happy that my fix works... I'm still unable to replicate the error on my end (also on arch with ttf-roboto installed). Using the original code where you are experiencing the error, running the following commands I get these outputs:

```
>>> get_system_fonts()['Roboto']['Regular']
'/usr/share/fonts/TTF/Roboto-Regular.ttf'
>>> get_system_fonts()['Roboto Condensed']['Regular']
'/usr/share/fonts/TTF/RobotoCondensed-Regular.ttf'
>>> FONTS_DICT['Roboto']['Regular']
'/usr/share/fonts/TTF/Roboto-Regular.ttf'
>>> find_font_info(DEFAULT_FONT)
('Roboto', 'Regular')
```

Are you able to show me what you get if you run the following:
```
$ python
>>> import sys
>>> sys.path.append("/usr/lib/python3.11/site-packages/streamdeck_ui/")
>>> exec(open("/usr/lib/python3.11/site-packages/streamdeck_ui/modules/fonts.py").read())
>>> get_system_fonts()['Roboto']['Regular']
>>> get_system_fonts()['Roboto Condensed']['Regular']
>>> FONTS_DICT['Roboto']['Regular']
>>> find_font_info(DEFAULT_FONT)
```

And for easy copy/pasting:
```
import sys
sys.path.append("/usr/lib/python3.11/site-packages/streamdeck_ui/")
exec(open("/usr/lib/python3.11/site-packages/streamdeck_ui/modules/fonts.py").read())
get_system_fonts()['Roboto']['Regular']
get_system_fonts()['Roboto Condensed']['Regular']
FONTS_DICT['Roboto']['Regular']
find_font_info(DEFAULT_FONT)
```

**Comment by teras** [comment]
```python
⋊> ~ python                                                                                                                                                19:01:16
Python 3.11.6 (main, Nov 14 2023, 09:36:21) [GCC 13.2.1 20230801] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.path.append("/usr/lib/python3.11/site-packages/streamdeck_ui/")
>>> exec(open("/usr/lib/python3.11/site-packages/streamdeck_ui/modules/fonts.py").read())
>>> get_system_fonts()['Roboto']['Regular']
'/home/teras/.fonts/r/Roboto_Regular.ttf'
>>> get_system_fonts()['Roboto Condensed']['Regular']
'/usr/share/fonts/TTF/RobotoCondensed-Regular.ttf'
>>> FONTS_DICT['Roboto']['Regular']
'/usr/lib/python3.11/site-packages/streamdeck_ui/fonts/roboto/Roboto-Regular.ttf'
>>> find_font_info(DEFAULT_FONT)
('Roboto', 'Regular')
>>> 
```

Maybe the file under `~/.fonts` ?

**Comment by ajbucci** [comment]
@teras You're using the fixed code I sent? I notice you don't have an error. But yeah! That file would cause the error for sure, since it's named `Roboto_Regular.ttf` instead of `Roboto-Regular.ttf`. Thanks for helping me to debug this!

**Comment by teras** [comment]
> @teras You're using the fixed code I sent? 

The lazy **copy & paste** version :laughing:

**Comment by ajbucci** [comment]
:smile: lazy == efficient

I'm glad I understand what's going on now. I'll go ahead and submit a PR with the proposed fix. Thanks again for your assistance!

**Comment by 4s3ti** [comment]
https://github.com/streamdeck-linux-gui/streamdeck-linux-gui/releases/tag/v4.1.0
