### ISSUE TITLE
[BUG]: Streamdeck slowing down shutdowns / reboots

### ISSUE THREAD

**Issue by Razer0123** [streamdeck-linux-gui/streamdeck-linux-gui#122]
### In raising this issue I confirm that

- [X] I have fully completed the issue template
- [X] I have searched open and closed issues for duplicates
- [X] I have read the [Contribution Guidelines](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/contributing/contributing-guide/)
- [X] I have read the [Code of Conduct](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/contributing/code-of-conduct/)
- [X] I have read the [Documentation](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/)

### Describe the bug

Hello, this app costantly slows down my reboots, i have to wait 45 seconds

### Steps to reproduce the behavior

Just reboot with the app  open

### Expected behavior

Reboot without issues

### Screenshots

![IMG_7486](https://github.com/streamdeck-linux-gui/streamdeck-linux-gui/assets/1551395/f9d0ab6d-8a64-403e-8a96-b28dfc7ac4ab)

### System Information

- Fedora 39
- Gnome

### Stream Deck Version

Stream Deck MK.2

**Comment by ajbucci** [comment]
What install method did you use? Can you paste any relevant output from ```journalctl --boot=-1 -n 1000```?

**Comment by Razer0123** [comment]
> journalctl

I installed via make

Could not find it with the command you sent me, any way to open the log using Gedit for example? so i could use search

**Comment by ajbucci** [comment]
journalctl uses the 'less' terminal pager, if you type ```/``` it will open a prompt at the bottom of the terminal that you can type a search query into. Try ```journalctl --boot=-1``` and then use ```/``` to search for stream deck.

**Comment by rdnelson** [comment]
I managed to reproduce this on arch by starting and stopping the systemd service manually.

```sh
# Ran quickly and started in the background
systemd --user start streamdeck.service

# Hung until systemd timed out and issued SIGKILL
systemd --user stop streamdeck.service
```

It appeared as though the `CLIStreamDeckServer` wasn't being shut down when a SIGTERM was received, and since that thread was waiting for incoming connections on a socket, it blocked the shutdown of the rest of the app. #135 should add the extra shutdown code for the CLI server, and I saw the application exiting properly upon receiving SIGTERM.
