### ISSUE TITLE
[BUG]: Cli commands do not work

### ISSUE THREAD

**Issue by marvin1099** [streamdeck-linux-gui/streamdeck-linux-gui#123]
### In raising this issue I confirm that

- [X] I have fully completed the issue template
- [X] I have searched open and closed issues for duplicates
- [X] I have read the [Contribution Guidelines](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/contributing/contributing-guide/)
- [X] I have read the [Code of Conduct](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/contributing/code-of-conduct/)
- [X] I have read the [Documentation](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/)

### Describe the bug

I Wanted to change the content of a button
The streamdeckc command is also not returning anything so i have no idea if it is even doing anything
There don't seem be be any documentation on the cli tool, at least i could not find any.
To start the progamm i just ran streamdeck in a terminal window (probably not relavant).

### Steps to reproduce the behavior

running any cli command as i can see (like):
streamdeckc -d 1 -p 1 -b 1 -s 1 --text new

### Expected behavior

The text of Button 1 should change to new

### Screenshots

![image](https://github.com/streamdeck-linux-gui/streamdeck-linux-gui/assets/40715852/3d142e8c-51e8-43d9-9259-ae7cc54401ef)

### System Information

I tryed version 4.0.0-1 (from the aur) and version 4.0.0-r4-ga4f5ce2-1 (also from the aur) 

### Stream Deck Version

Standart

**Comment by marvin1099** [comment]
Update: I have now confirmed that installing streamdeck-linux-gui via pipx (so is a other way to make a virt. enviroment) has the same problem. The aur version is probably the save as the pip version but i couldn't hut to try.
Any and all help is appreciated.

**Comment by bmlandis2010** [comment]
I had a similar issue. The INDEX number for the --deck, --page, --button, and --state parameters actually starts at 0, not 1. I haven't been able to get the --deck parameter to work with any value, so I omit it from my commands so it will use the currently selected deck in the UI. You also need to add the --action (-a) parameter.

Try this command:
`streamdeckc -a SET_TEXT -p 0 -b 0 -s 0 --text new`

I also just discovered that the --state (-s) parameter is being ignored (except with -a SET_STATE) and the current state is used instead. That can be worked around by setting the desired state before making changes to it:
`streamdeckc -a SET_STATE -p 0 -b 0 -s 1`

**Comment by marvin1099** [comment]
yes that seems tho work if anyone reads this cam you point me to the file where i can read all actions in the codebase.
i assume there is a severe running in the background and i like to know all my options.

**Comment by marvin1099** [comment]
Yes, it seams it has all the actions are listed there i must have missed that.

**Comment by v4u6h4n** [comment]
I ask that that a small addition be made to the streamdeckc --help that explains that all pages, buttons and states start with 0 and not 1, its a bit counter-intuitive, at least for a novice linux user like myself, as all the GUI components starts with 1 and not 0.
