### ISSUE TITLE
[BUG]: Image Doesnt Update When Selecting New File with Same File Name

### ISSUE THREAD

**Issue by v4u6h4n** [streamdeck-linux-gui/streamdeck-linux-gui#126]
### In raising this issue I confirm that

- [X] I have fully completed the issue template
- [X] I have searched open and closed issues for duplicates
- [X] I have read the [Contribution Guidelines](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/contributing/contributing-guide/)
- [X] I have read the [Code of Conduct](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/contributing/code-of-conduct/)
- [X] I have read the [Documentation](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/)

### Describe the bug

Hey everyone :-) Thanks of working on this project, I wouldnt be able to stream on linux without it!

I noticed that if I select a new image with the same file name and path, the image on the physical button will not update, even if the image on the software button does. I noticed this because I was editing the padding of different icons and then reselecting the same file to get it right and I had to restart the service to get it to update.

### Steps to reproduce the behavior

Edit an already assigned image and then assign the image to the button.

### Expected behavior

Update image displayer on physical button.

### System Information

Debian 12
KDE Plasma
Wayland
4.0

### Stream Deck Version

Elgato Stream Deck Mini

**Comment by ajbucci** [comment]
@v4u6h4n what happens if you click the red x to remove the image and then re-add it?

**Comment by ajbucci** [comment]
If I understand the code correctly, I think the issue is that currently the images are cached based on a hash generated with the file name.

https://github.com/streamdeck-linux-gui/streamdeck-linux-gui/blob/main/streamdeck_ui%2Fdisplay%2Fimage_filter.py#L30

I'll investigate some more.

**Comment by v4u6h4n** [comment]
Hey ajbucci :-)

Oh I see, that makes sense. I can see if that workaround you mentioned would work once I've finished migrating from Debian to Arch.

**Comment by ajbucci** [comment]
Hi :) I don't think the workaround I had mentioned before the edit would work because I don't think it clears the cache. I had tried naively invoking the image removal code before loading the next image as a quick fix in hopes of refreshing the cache but it didn't result in a change in behavior.

**Comment by 4s3ti** [comment]
https://github.com/streamdeck-linux-gui/streamdeck-linux-gui/releases/tag/v4.1.0

**Comment by v4u6h4n** [comment]
Thanks!
