### ISSUE TITLE
[BUG]: after upgrading to Ubuntu 23.10, streamdeck-ui is not showing any devices

### ISSUE THREAD

**Issue by Jmoney1536** [streamdeck-linux-gui/streamdeck-linux-gui#139]
### In raising this issue I confirm that

- [X] I have fully completed the issue template
- [X] I have searched open and closed issues for duplicates
- [X] I have read the [Contribution Guidelines](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/contributing/contributing-guide/)
- [X] I have read the [Code of Conduct](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/contributing/code-of-conduct/)
- [X] I have read the [Documentation](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/)

### Describe the bug

after upgrading to Ubuntu 23.10, streamdeck-ui is not showing any devices

### Steps to reproduce the behavior

After I upgraded my Ubuntu to 23.10, streamdeck-ui is no longer showing any elgato devices.  I have uninstalled and purged it fully and re-installed twice; once using the basic command lines and again using the pre-built ubuntu script.  It will install and run, but shows no devices available on the drop-down so it is kinda useless for me right now.  I  do get the following text when starting it within Terminal:        

qt.dbus.integration: Could not connect "org.freedesktop.IBus" to globalEngineChanged(QString)
Exception in thread Thread-1 (_run):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jj/.local/lib/python3.11/site-packages/streamdeck_ui/stream_deck_monitor.py", line 113, in _run
    self.attached(streamdeck_id, streamdeck)
  File "/home/jj/.local/lib/python3.11/site-packages/streamdeck_ui/api.py", line 188, in attached
    self.update_streamdeck_filters(serial_number)
  File "/home/jj/.local/lib/python3.11/site-packages/streamdeck_ui/api.py", line 479, in update_streamdeck_filters
    self.update_button_filters(serial_number, page, button)
  File "/home/jj/.local/lib/python3.11/site-packages/streamdeck_ui/api.py", line 514, in update_button_filters
    display_handler.replace(page, button, filters)
  File "/home/jj/.local/lib/python3.11/site-packages/streamdeck_ui/display/display_grid.py", line 79, in replace
    filter.initialize(self.size)
  File "/home/jj/.local/lib/python3.11/site-packages/streamdeck_ui/display/text_filter.py", line 43, in initialize
    label_w, _ = backdrop_draw.textsize(self.text, font=self.true_font)
                 ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ImageDraw' object has no attribute 'textsize'

Not sure if something got corrupted or I didn't uninstall fully or not, but I have checked multiple times and the udev file is showing the correct text and this has only surfaced since I upgraded my OS, so also not sure if it removed something necessary on the update??

### Expected behavior

I expect the program to show my device as it had before I upgraded my OS.

### System Information

OS:  Ubuntu 23.10 
Desktop Environment:  Gnome

### Stream Deck Version

Standard 15-key

**Comment by rkmax** [comment]
@Jmoney1536 which version did you have installed. I think the problem here is related to a method that was deprecated in pillow and in somehow the ubuntu upgrade upgrate pillow to version 10. I think upading the version of the app should fix the issue

**Comment by Jmoney1536** [comment]
OK!  So I FINALLY got it to work.  Fully removed everything again and made sure to purge all leftover files (apparently, I had both the streamdeck-linux-sui AND streamdeck-ui folders in my pipx directory; maybe this was causing this issue, I dunno).

**Comment by 4s3ti** [comment]
Glad that you figured it out. 

yes v2.0.15 is the version from the old repository. Even thought the packages are different the executable is the same therefore you have to completely remove v2 before installing v3 or above.
