### ISSUE TITLE
[BUG]: Key Press action returns error, does not happen. 

### ISSUE THREAD

**Issue by Kerbal01** [streamdeck-linux-gui/streamdeck-linux-gui#141]
### In raising this issue I confirm that

- [X] I have fully completed the issue template
- [X] I have searched open and closed issues for duplicates
- [X] I have read the [Contribution Guidelines](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/contributing/contributing-guide/)
- [X] I have read the [Code of Conduct](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/contributing/code-of-conduct/)
- [X] I have read the [Documentation](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/)

### Describe the bug

Button press should lead to action (I only have key presses set up currently).  Action does not occur, system notification reports "Warning: Unable to perform key press action. 'str' object cannot be interpreted as an integer.

 I'm running Wayland which the documentation explicitly says wont work for key press actions, but it worked as expected for 2 months after I installed the program. I have updated the system several times and the program kept working as expected each time. After a boot yesterday (last update several days ago), started getting the error. I switched to an X11 session and the bug persists. 

### Steps to reproduce the behavior

1: configure button action
2: press button on Stream Deck
3: get warning from system with error message, key press action does not happen.

### Expected behavior

1: press button
2: key press action occurs

### Screenshots

![Screenshot_20240101_150108](https://github.com/streamdeck-linux-gui/streamdeck-linux-gui/assets/29660014/7055c0a2-6403-402f-b43b-f941e8daf9ba)

### System Information

OS: Arch Linux (Garuda)
DE: KDE (Wayland)
Python version: 3.11.6

### Stream Deck Version

XL

**Comment by ajbucci** [comment]
New keypress logic needs to initialize UInput with the linux event code integer constants instead of their names. I'll submit a PR with a fix.

**Comment by 4s3ti** [comment]
https://github.com/streamdeck-linux-gui/streamdeck-linux-gui/releases/tag/v4.1.0
