### ISSUE TITLE
[BUG]: Could not load the Qt platform plugin

### ISSUE THREAD

**Issue by Stef500** [streamdeck-linux-gui/streamdeck-linux-gui#146]
### In raising this issue I confirm that

- [X] I have fully completed the issue template
- [X] I have searched open and closed issues for duplicates
- [X] I have read the [Contribution Guidelines](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/contributing/contributing-guide/)
- [X] I have read the [Code of Conduct](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/contributing/code-of-conduct/)
- [X] I have read the [Documentation](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/)

### Describe the bug

Hi, 
Here is the message error that I get :

"qt.qpa.plugin: From 6.5.0, xcb-cursor0 or libxcb-cursor0 is needed to load the Qt xcb platform plugin.
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: linuxfb, minimal, vkkhrdisplay, xcb, eglfs, minimalegl, wayland-egl, wayland, vnc, offscreen.

Abandon (core dumped)
".

### Steps to reproduce the behavior

Type streamdeck in terminal

### Expected behavior

launch app with GUI ?

### System Information

Mint 20.2

### Stream Deck Version

Mini

**Comment by Stef500** [comment]
In fact it was a problem with pip not the application. Sorry for the disturbance !

**Comment by zcolor** [comment]
Hi, I'm having the same issue.

What how did you solve yours?

**Comment by Stef500** [comment]
> Hi, I'm having the same issue.
> 
> What how did you solve yours?
> 

Hi, I did a full reinstall

**Comment by zcolor** [comment]
I tried that and I'm still getting the same issue even after doing a full reinstall. I'm on Rocky 8 though.
