### ISSUE TITLE
[BUG]: Maybe Wayland

### ISSUE THREAD

**Issue by rastarr** [streamdeck-linux-gui/streamdeck-linux-gui#159]
### In raising this issue I confirm that

- [X] I have fully completed the issue template
- [X] I have searched open and closed issues for duplicates
- [X] I have read the [Contribution Guidelines](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/contributing/contributing-guide/)
- [X] I have read the [Code of Conduct](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/contributing/code-of-conduct/)
- [X] I have read the [Documentation](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/)

### Describe the bug

I've been trying to get this to work under nixOS, swayvm and Wayland.
While i can connect to my Streamdeck XL and try and set it to do some functions, nothing is output.

Is this because streakdeck-ui is not wayland ready?

### Steps to reproduce the behavior

install Wayland and test
I presume it won't work but prove me wrong :)

### Expected behavior

Expecting to work under Wayland

### System Information

OS - Linux NixOS

### Stream Deck Version

XL

**Comment by 4s3ti** [comment]
I am using it on Sway + wayland, therefore It should work but some functionality such as "writing" text is still being tested. 

Latest master branch should have some support for "writing text" already.
