### ISSUE TITLE
[BUG]: Typo in discussion category

### ISSUE THREAD

**Issue by sftim** [streamdeck-linux-gui/streamdeck-linux-gui#16]
### In raising this issue I confirm that

- [X] I have fully completed the issue template
- [X] I have searched open and closed issues for duplicates
- [X] I have read the [Contribution Guidelines](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/contributing/contributing-guide/)
- [X] I have read the [Code of Conduct](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/contributing/code-of-conduct/)
- [X] I have read the [Documentation](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/)

### Describe the bug

One of the discussion categories, https://github.com/streamdeck-linux-gui/streamdeck-linux-gui/discussions/categories/ideas-feature-requets, has a typo in its name.

### Steps to reproduce the behavior

- Visit https://github.com/streamdeck-linux-gui/streamdeck-linux-gui/discussions/categories/ideas-feature-requets
- Check the spelling of “requests”

### Expected behavior

“requests”

### System Information

n/a

### Stream Deck Version

Standard

**Comment by 4s3ti** [comment]
Done, Thank you for calling out!
