### ISSUE TITLE
[BUG]: Streamdeck fails to start due to missing udev rules

### ISSUE THREAD

**Issue by 4s3ti** [streamdeck-linux-gui/streamdeck-linux-gui#163]
### In raising this issue I confirm that

- [X] I have fully completed the issue template
- [X] I have searched open and closed issues for duplicates
- [X] I have read the [Contribution Guidelines](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/contributing/contributing-guide/)
- [X] I have read the [Code of Conduct](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/contributing/code-of-conduct/)
- [X] I have read the [Documentation](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/)

### Describe the bug

Application fails to startup with following error: 

```
Traceback (most recent call last):
  File "/usr/bin/streamdeck", line 5, in <module>
    from streamdeck_ui.gui import start
  File "/usr/lib/python3.11/site-packages/streamdeck_ui/gui.py", line 46, in <module>
    from streamdeck_ui.modules.keyboard import KeyPressAutoComplete, keyboard_press_keys, keyboard_write
  File "/usr/lib/python3.11/site-packages/streamdeck_ui/modules/keyboard.py", line 215, in <module>
    _UINPUT = UInput({e.EV_KEY: _SUPPORTED_KEY_CONSTANTS})
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/evdev/uinput.py", line 124, in __init__
    self._verify()
  File "/usr/lib/python3.11/site-packages/evdev/uinput.py", line 271, in _verify
    raise UInputError(msg.format(self.devnode))
evdev.uinput.UInputError: "/dev/uinput" cannot be opened for writing
```

Solution seems to be adding new udev rule: 

```
KERNEL=="uinput", SUBSYSTEM=="misc", OPTIONS+="static_node=uinput", TAG+="uaccess", GROUP="input", MODE="0660"
```

### Steps to reproduce the behavior

1. Update to latest master (on commit: https://github.com/streamdeck-linux-gui/streamdeck-linux-gui/commit/735b2380f143165f873f6436d572d34ce7e2c7f4)
2. Launch application and verify the error

### Expected behavior

Application should launch

### System Information

```
                   -`                    f0rs3ti@deathstar
                  .o+`                   -----------------
                 `ooo/                   OS: Arch Linux x86_64
                `+oooo:                  Host: MS-7C84 1.0
               `+oooooo:                 Kernel: 6.7.1-zen1-1-zen
               -+oooooo+:                Uptime: 8 mins
             `/:-:++oooo+:               Packages: 1257 (pacman), 6 (flatpak)
            `/++++/+++++++:              Shell: bash 5.2.26
           `/++++++++++++++:             Resolution: 5120x1440
          `/+++ooooooooooooo/`           WM: sway
         ./ooosssso++osssssso+`          Terminal: tmux
        .oossssso-````/ossssss+`         CPU: AMD Ryzen 7 5800X (16) @ 3.800GHz
       -osssssso.      :ssssssso.        GPU: AMD ATI Radeon RX 6700/6700 XT/6750 XT / 6800M/6850M XT
      :osssssss/        osssso+++.       Memory: 5726MiB / 32015MiB
     /ossssssss/        +ssssooo/-
   `/ossssso+/:-        -:/+osssso+-
  `+sso+:-`                 `.-/+oso:
 `++:.                           `-/+/
 .`                                 `/
```

### Stream Deck Version

```
git describe --long --tags --exclude='*[a-zA-Z][a-zA-Z]*' | sed -E 's/^v//;s/([^-]*-g)/r\1/;s/-/./g'
4.1.0.r5.g735b238
```

**Comment by 4s3ti** [comment]
Needs to be verified if more users are getting affected by it, and added to documentation.

**Comment by dhtseany** [comment]
Hello, I maintain the package on the AUR, can you please confirm the
model of Streamdeck that you have?

**Comment by 4s3ti** [comment]
@dhtseany the streamdeck mk.2 

```
Bus 005 Device 008: ID 0fd9:0080 Elgato Systems GmbH Stream Deck MK.2
```

**Comment by ajbucci** [comment]
Before this commit a new UInput device was being initialized every time a user used "write text" or "press keys", so users that weren't using those functions would not have experienced the error, since a UInput device would never be initialized. Since we are now _globally_ initializing a single UInput device this error will impact some subset of users that don't have the appropriate udev rules.

**Comment by ajbucci** [comment]
This PR will allow the app to start, but if they don't have the proper udev rules then they will not be able to write text or press keys

**Comment by dhtseany** [comment]
I'll have the PKGBUILD updated to reflect the newly added udev rules
once they're included in the next numbered release as the tag for
4.1.0 doesn't include the new folder yet.

**Comment by joaojotta** [comment]
Hi
Sorry to add to the fire but here's a different error I've been having since yesterday.
_(tell me if I should open a different issue)_

running `streamdeckc`
```
Traceback (most recent call last):
  File "/usr/bin/streamdeckc", line 8, in <module>
    sys.exit(execute())
             ^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/streamdeck_ui/cli/server.py", line 167, in execute
    sock.connect(path)
FileNotFoundError: [Errno 2] No such file or directory
****
```

running `streamdeck`
```
Exception in thread Thread-1 (_run):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.11/site-packages/streamdeck_ui/stream_deck_monitor.py", line 117, in _run
    self.attached(streamdeck_id, streamdeck)
  File "/usr/lib/python3.11/site-packages/streamdeck_ui/api.py", line 203, in _on_steam_deck_attached
    self._update_streamdeck_filters(serial_number)
  File "/usr/lib/python3.11/site-packages/streamdeck_ui/api.py", line 658, in _update_streamdeck_filters
    self._update_button_filters(serial_number, page, button)
  File "/usr/lib/python3.11/site-packages/streamdeck_ui/api.py", line 691, in _update_button_filters
    TextFilter(
  File "/usr/lib/python3.11/site-packages/streamdeck_ui/display/text_filter.py", line 25, in __init__
    self.true_font = ImageFont.truetype(font, font_size)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/PIL/ImageFont.py", line 819, in truetype
    return freetype(font)
           ^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/PIL/ImageFont.py", line 816, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/PIL/ImageFont.py", line 245, in __init__
    self.font = core.getfont(
                ^^^^^^^^^^^^^
OSError: cannot open resource
```

In the first case I get nothing. In the second one I do get the UI but with no Streamdeck connected.
I've tried the Streamdeck on other devices to check if it's broken or something. It's not.

**Comment by ajbucci** [comment]
@joaojotta hi, yes can you create a new issue? Also include Linux distribution, installation method etc

**Comment by 4s3ti** [comment]
Updated the title of this issue to be more descriptive. @joaojotta  create a new issue or discussion for your case, as your issue is not at all related with this one.

**Comment by joaojotta** [comment]
Done. Thanks!
Should we delete these posts just to clear out the thread? I wouldn't mind. 😉
