### ISSUE TITLE
[BUG]: Stream Deck ceased to be recognized by streamdeck-linux-gui

### ISSUE THREAD

**Issue by joaojotta** [streamdeck-linux-gui/streamdeck-linux-gui#167]
### In raising this issue I confirm that

- [X] I have fully completed the issue template
- [X] I have searched open and closed issues for duplicates
- [X] I have read the [Contribution Guidelines](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/contributing/contributing-guide/)
- [X] I have read the [Code of Conduct](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/contributing/code-of-conduct/)
- [X] I have read the [Documentation](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/)

### Describe the bug

Hi!
For the last 24 hours (with up to date system) my Stream Deck ceased to be recognized by streamdeck-linux-gui.
I've tested it on other systems and it still works (was afraid it got damaged somehow).
Please tell me if more info is required.

### Steps to reproduce the behavior

running `streamdeckc` does not bring up the GUI
```
Traceback (most recent call last):
  File "/usr/bin/streamdeckc", line 8, in <module>
    sys.exit(execute())
             ^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/streamdeck_ui/cli/server.py", line 167, in execute
    sock.connect(path)
FileNotFoundError: [Errno 2] No such file or directory
****
```

running `streamdeck` brings up the GUI
```
Exception in thread Thread-1 (_run):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.11/site-packages/streamdeck_ui/stream_deck_monitor.py", line 117, in _run
    self.attached(streamdeck_id, streamdeck)
  File "/usr/lib/python3.11/site-packages/streamdeck_ui/api.py", line 203, in _on_steam_deck_attached
    self._update_streamdeck_filters(serial_number)
  File "/usr/lib/python3.11/site-packages/streamdeck_ui/api.py", line 658, in _update_streamdeck_filters
    self._update_button_filters(serial_number, page, button)
  File "/usr/lib/python3.11/site-packages/streamdeck_ui/api.py", line 691, in _update_button_filters
    TextFilter(
  File "/usr/lib/python3.11/site-packages/streamdeck_ui/display/text_filter.py", line 25, in __init__
    self.true_font = ImageFont.truetype(font, font_size)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/PIL/ImageFont.py", line 819, in truetype
    return freetype(font)
           ^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/PIL/ImageFont.py", line 816, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/PIL/ImageFont.py", line 245, in __init__
    self.font = core.getfont(
                ^^^^^^^^^^^^^
OSError: cannot open resource
```

### Expected behavior

In the first case I get nothing. In the second one I do get the UI but with no Streamdeck connected.
I've tried the Streamdeck on other devices to check if it's broken or something. It's not.

### Screenshots

![image](https://github.com/streamdeck-linux-gui/streamdeck-linux-gui/assets/11931285/2d378646-92fe-4eeb-a463-8d549860f3fb)

### System Information

OS: Arch Linux x86_64
Kernel: 6.7.3-arch1-1
Shell: bash 5.2.26
Display (PHL098C): 3440x1440 @ 120Hz
DE: KDE Plasma 5.27.10
WM: KWin (X11)
CPU: 13th Gen Intel(R) Core(TM) i5-13400 (16) @ 4.60 GHz
GPU: NVIDIA GeForce RTX 3060
Memory: 3.41 GiB / 62.61 GiB (5%)
Swap: 12.06 MiB / 4.00 GiB (0%)

### Stream Deck Version

Stream Deck MK.2

**Comment by ajbucci** [comment]
@joaojotta thanks for opening a separate issue!

Was this an AUR install / did you ever install using any of the other methods? What version of streamdeck-linux-gui are you running?

**Comment by joaojotta** [comment]
I knew I forgot something!
I installed via AUR (using paru) as that's as far as my technical skills go.

Version 4.1.0
streamdeck 0.9.5
pyside6 6.6.1
pillow 10.2.0
pynput 1.7.6

**Comment by ajbucci** [comment]
Is it a fresh install / config?

**Comment by joaojotta** [comment]
Maybe 3 week old. Tried it on other systems (all Arch) and the same happens (but it works on Eindows so it’s not broken).

**Comment by 4s3ti** [comment]
it seems that the Fonts issue is still haunting us ... 
Do you have roboto font?  think that's the default ...

**Comment by joaojotta** [comment]
Maybe I do, maybe I don’t. I have to check. I do remember it having the Roboto font as default…
I’ll try it as soon as I get a chance but won’t until Thursday night/Friday morning.
Any specific folder to install the font? I am currently trying to instal in ~/.fonts because I used to install in /usr/share/fonts.

Thanks!

**Comment by joaojotta** [comment]
So: made sure the Roboto font was present (it is) and it's all the same so far.

**Comment by joaojotta** [comment]
### Update
After many attempts to make it work, I've managed to install this on Ubuntu Studio. All was working until I imported the profile I was using and it all came to the same.
This made me think about the Roboto font you mentioned and tried everything I could until I made it work.
The problem? I can't tell for sure but after messing around I figured if the font is not present, the interface just "crashes" and you cease to see the Stream Deck as a connected device in the GUI.

So, it you have the same problem, this is what you can do:

Edit a configuration file (make sure you always have one - I don't know where the app keeps it's copy), and edit all `font` lines to `"font": "",`.
Save it, import it (restart the app if needed) and it should work now.
I must remind you that the font may be present but it must be installed in the same path as in the profile setting.

**Comment by joaojotta** [comment]
_Should I keep it opened so people can better check it out?
Should this be in the troubleshoot section?_

**Comment by 4s3ti** [comment]
I think you can leave it open ... ill mark it as a bug ..seems the Font implementation still has its issues and quirks

**Comment by ajbucci** [comment]
Can you share the font entry that was causing it to crash?

**Comment by joaojotta** [comment]
"font": "/usr/share/fonts/myFonts/Trenda/Desktop/Trenda-ThinIt.ttf", was one of them but it's not about the fonts themselves but about being present or not.
I ended up changing them **ALL** to a font I knew it worked (because I tested it on another machine).
So I can't tell you for sure if it was this _Trenda_ font of _Roboto_ of even _Config Rounded_ that I now use on **ALL** of them.
Maybe automatically changing fonts that are not available to _Roboto_ or _Noto_ or something would fix this...

**Comment by ajbucci** [comment]
Thanks! It looks like you just don't have that font installed on that PC or if it is it's installed in a different location. I didn't think about this use-case between different PCs. I will modify the code to fall back to the default font in this case.

**Comment by joaojotta** [comment]
> Thanks! It looks like you don't have that font installed on that PC or if it is it's installed in a different location. I didn't think about the use case of sharing a config between different PCs. I will modify the code to fall back to the default font in this case.

Well, it's hard to argue with that but it's also hard to figure out why it just stopped working. I did move fonts around but not _Roboto_. Maybe _Trenda_, yes.
Still: the font kept working in all apps.

I'd suggest streamdeck-linux-ui should look font fonts under `~/.fonts` witch is where I have my own fonts installed and maybe more people do too.

**Comment by ajbucci** [comment]
The issue is that the config file is saved with the absolute path of the font. So when you moved Trenda it could no longer locate a font at the path specified in the config. It probably _does_ know where Trenda is when it builds its font listing, since it uses the system utility fc-list to discover fonts.

The solution here is probably two parts:

1) Check if the path to the font file specified in the config exists, if it doesn't, search for the font file name in the font listing and change the path to the valid font file path if it exists elsewhere
2) If the app is unable to set a font, use the default font instead. I don't think we _ever_ want to crash the program entirely just because we were unable to apply a font
