### ISSUE TITLE
[BUG]: "delay" keyword does not parse.

### ISSUE THREAD

**Issue by JorranSteele** [streamdeck-linux-gui/streamdeck-linux-gui#185]
### In raising this issue I confirm that

- [X] I have fully completed the issue template
- [X] I have searched open and closed issues for duplicates
- [X] I have read the [Contribution Guidelines](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/contributing/contributing-guide/)
- [X] I have read the [Code of Conduct](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/contributing/code-of-conduct/)
- [X] I have read the [Documentation](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/)

### Describe the bug

I was trying to create key press buttons for a game I'm playing and the "delay" keyword does not seem to parse correctly whether I specify a delay interval or not. Does not seem to matter if the "delay" keyword is added via the "+" modifier or as it's own key press group. 

### Steps to reproduce the behavior

1. Configure action "Press keys:" with something like, "home,delay,up,delay,up,delay,down"
2. Press button on Stream Deck Plus
3. Receive error, "Warning. Unable to perform key press action. Invalid keys:['delay']"

### Expected behavior

Key press actions to be performed with the default 0.5 second delay.

### Screenshots

![Screenshot_20211052](https://github.com/streamdeck-linux-gui/streamdeck-linux-gui/assets/43096061/6c8ea9c7-c915-48ba-9c65-953325e79ccc)

![Screenshot_20211050](https://github.com/streamdeck-linux-gui/streamdeck-linux-gui/assets/43096061/865f300b-7268-40b4-b4e0-9ea8b280705f)  

### System Information

OS: Garuda Linux (Arch derivative)
Kernel: 6.7.8-zen1-1-zen
DE: Plasma 5.27.10
WM: KWin
Session: X11
Python 3.11.7
StreamDeck UI Version: 4.1.1

### Stream Deck Version

Stream Deck Plus (+)

**Comment by ajbucci** [comment]
It looks like this functionality was (probably accidentally) removed when we transitioned to UInput. I will go ahead and add it back in.

**Comment by yesrod** [comment]
In version 4.0.0 the `delay` command works still.

I also have some hex keycodes for the numpad keys like `0xFF9F` that uinput is similarly complaining about.

**Comment by ctyler2621** [comment]
Any timeframe for a release with the delay functionality fixed?

**Comment by 4s3ti** [comment]
> Any timeframe for a release with the delay functionality fixed?

No, depends on how fast someone makes a pull request and if I have the ability to review it or not, or if any of the other contributors is actually available and wants to review it.

**Comment by ajbucci** [comment]
I'll submit a PR for this sometime this weekend
