### ISSUE TITLE
[BUG]: Can't select buttons in GUI

### ISSUE THREAD

**Issue by v4u6h4n** [streamdeck-linux-gui/streamdeck-linux-gui#200]
### In raising this issue I confirm that

- [X] I have fully completed the issue template
- [X] I have searched open and closed issues for duplicates
- [X] I have read the [Contribution Guidelines](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/contributing/contributing-guide/)
- [X] I have read the [Code of Conduct](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/contributing/code-of-conduct/)
- [X] I have read the [Documentation](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/)

### Describe the bug

After months of use without issues, suddenly I can't select any buttons on any page of any of my streamdecks in the GUI. If I click and hold I can drag, but if I click and release I see the button selection highlighted border flash momentarily, but it does not remain selected. Any help would be appreciated, as I'm lost as to what the cause might be, and is unusable at the moment.

### Steps to reproduce the behavior

1. Click a button.

### Expected behavior

Button selection.

### System Information

OS: Arch, Hyprland
Python: 3.9

### Stream Deck Version

Mini

**Comment by CorgiZack** [comment]
On a fresh install of Linux Mint 21.3 Cinnamon, I'm experiencing the same thing. If it helps:

Traceback (most recent call last):
  File "/home/zack/.local/share/pipx/venvs/streamdeck-linux-gui/lib/python3.10/site-packages/streamdeck_ui/gui.py", line 940, in <lambda>
    lambda current_button=button, all_buttons=buttons: button_clicked(current_button, all_buttons)
  File "/home/zack/.local/share/pipx/venvs/streamdeck-linux-gui/lib/python3.10/site-packages/streamdeck_ui/gui.py", line 498, in button_clicked
    if not selected_button.isChecked():
AttributeError: 'bool' object has no attribute 'isChecked'

I see this whenever I click a button in the GUI.
