### ISSUE TITLE
[BUG]: Stopped working again and it isn't about the font

### ISSUE THREAD

**Issue by joaojotta** [streamdeck-linux-gui/streamdeck-linux-gui#210]
### In raising this issue I confirm that

- [X] I have fully completed the issue template
- [X] I have searched open and closed issues for duplicates
- [X] I have read the [Contribution Guidelines](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/contributing/contributing-guide/)
- [X] I have read the [Code of Conduct](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/contributing/code-of-conduct/)
- [X] I have read the [Documentation](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/)

### Describe the bug

From some update ago streamdeck-linux-gui stopped working.

### Steps to reproduce the behavior

**streamdeck**
```
Traceback (most recent call last):
  File "/usr/bin/streamdeck", line 5, in <module>
    from streamdeck_ui.gui import start
  File "/usr/lib/python3.12/site-packages/streamdeck_ui/gui.py", line 30, in <module>
    from streamdeck_ui.api import StreamDeckServer
  File "/usr/lib/python3.12/site-packages/streamdeck_ui/api.py", line 11, in <module>
    from StreamDeck.Devices import StreamDeck
ModuleNotFoundError: No module named 'StreamDeck'
```

**streamdeckc**
```
Traceback (most recent call last):
  File "/usr/bin/streamdeckc", line 5, in <module>
    from streamdeck_ui.cli.server import execute
  File "/usr/lib/python3.12/site-packages/streamdeck_ui/cli/server.py", line 9, in <module>
    from streamdeck_ui.api import StreamDeckServer
  File "/usr/lib/python3.12/site-packages/streamdeck_ui/api.py", line 11, in <module>
    from StreamDeck.Devices import StreamDeck
ModuleNotFoundError: No module named 'StreamDeck'
```

### Expected behavior

Should open the GUI.

### System Information

Arch
Kernel 6.8.8
Plasma 6.0.4

### Stream Deck Version

MK.2 (I guess - it's the one with 15 buttons)

**Comment by dhtseany** [comment]
Hello, you have to clean-build both streamdeck-ui as well as python-elgato-streamdeck which should then solves the problem.

**Comment by joaojotta** [comment]
It worked like a charm! THANKS!
