### ISSUE TITLE
[BUG]: Inputing text is too slow

### ISSUE THREAD

**Issue by ThibF** [streamdeck-linux-gui/streamdeck-linux-gui#219]
### In raising this issue I confirm that

- [X] I have fully completed the issue template
- [X] I have searched open and closed issues for duplicates
- [X] I have read the [Contribution Guidelines](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/contributing/contributing-guide/)
- [X] I have read the [Code of Conduct](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/contributing/code-of-conduct/)
- [X] I have read the [Documentation](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/)

### Describe the bug

Currently, when using the `write text` action, _DEFAULT_KEY_PRESS_DELAY in keyboard.py is set to be `0.05`.
This results in 100 char inputs to take more than 5 full seconds to be typed.

Manually playing with this value shows that it could be divided by 10 on my setup.
As I understand this can be application/setup dependent, not sure if the delay can be removed all together but having it configurable would be nice.

### Steps to reproduce the behavior

1. Type a long text in the `write text` section
2. Press the associated button
3. Wait for the message to be slowly typed

### Expected behavior

Faster typing speed

### System Information

Ubuntu 24.04
i3

### Stream Deck Version

Version 4.1.2

**Comment by coolapso** [comment]
Hi! Please read: https://github.com/streamdeck-linux-gui/streamdeck-linux-gui/discussions/203   and 

https://github.com/streamdeck-linux-gui/streamdeck-linux-gui/discussions/217
