### ISSUE TITLE
[FEATURE]: one single environment variable to set directory for configuration files

### ISSUE THREAD

**Issue by GsakuL** [streamdeck-linux-gui/streamdeck-linux-gui#220]
### In raising this issue I confirm that

- [X] I have fully completed the issue template
- [X] I have searched open and closed issues for duplicates
- [X] I have read the [Contribution Guidelines](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/contributing/contributing-guide/)
- [X] I have read the [Code of Conduct](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/contributing/code-of-conduct/)
- [X] I have read the [Documentation](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/)

### Describe the bug

I wanted to clean up my home directory ('~') when I noticed that the streamdeck-ui has it's confitg and log just straight in `~`. I looked at the code and found env var names. However the one for `.streamdeck_ui.json_old` is also missing entirely.

---

Since the implementation is rather straightforward, I'd like to contribute this myself. I'll also make it non-breaking for existing users

### Steps to reproduce the behavior

1. use streamdeck-ui
2. enable "hidden files" in your file manager or use `ls -lA ~`
3. see (amongst other files):
  - `.streamdeck_ui.json`
  - `.streamdeck_ui.json_old`
  - `.streamdeck_ui.log`

### Expected behavior

I'd like for the configuration to use `$XDG_CONFIG_HOME`, ie `~/.config/streamdeck-ui/`.
This would de-clutter my home dir.
But that's also not entirely possible with per-file env vars since the `json_old` has no env var.

Additionally, having a folder as env var, I'll have to only ever set that. In case the ui gets expanded some day and uses more files (aside from import/export, user-defined-icons, etc) (and other contributors adhere to this new change), the new files should also all land within that configuration folder.
I don't really care what the files are called in that directory, just that they are all there. "just change the base path".

### System Information

NixOS 24.05 / unstable
Desktop: Wayland KDE
Python 3.11.9 

### Stream Deck Version

Standard

**Comment by coolapso** [comment]
Hi, this is not going to be done / fixed. please read: https://github.com/streamdeck-linux-gui/streamdeck-linux-gui/discussions/203

**Comment by coolapso** [comment]
https://github.com/streamdeck-linux-gui/streamdeck-linux-gui/discussions/203

**Comment by GsakuL** [comment]
oh. Of course that's reasonable then.

sorry to bother
