### ISSUE TITLE
[BUG]: ModuleNotFoundError: No module named 'PIL.ImageQt' (Fedora 40)

### ISSUE THREAD

**Issue by MrDiamondDog** [streamdeck-linux-gui/streamdeck-linux-gui#225]
### In raising this issue I confirm that

- [X] I have fully completed the issue template
- [X] I have searched open and closed issues for duplicates
- [X] I have read the [Contribution Guidelines](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/contributing/contributing-guide/)
- [X] I have read the [Code of Conduct](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/contributing/code-of-conduct/)
- [X] I have read the [Documentation](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/)

### Describe the bug

Downloaded the python package, everything installed fine, and running `streamdeck` only results in the error:

```
Traceback (most recent call last):
  File "/home/mrdiamond/.local/bin/streamdeck", line 5, in <module>
    from streamdeck_ui.gui import start
  File "/home/mrdiamond/.local/lib/python3.12/site-packages/streamdeck_ui/gui.py", line 30, in <module>
    from streamdeck_ui.api import StreamDeckServer
  File "/home/mrdiamond/.local/lib/python3.12/site-packages/streamdeck_ui/api.py", line 8, in <module>
    from PIL.ImageQt import ImageQt
ModuleNotFoundError: No module named 'PIL.ImageQt'
```

### Steps to reproduce the behavior

1. Download streamdeck-linux-gui on Fedora 40
2. Run it
3. Error

### Expected behavior

No error

### System Information

OS: Fedora 40 Workstation
Env: GNOME + Xorg
Python: 3.12.4
Pip: 24.1.2

**Comment by coolapso** [comment]
https://github.com/streamdeck-linux-gui/streamdeck-linux-gui/issues/224
https://github.com/streamdeck-linux-gui/streamdeck-linux-gui/discussions/203
