### ISSUE TITLE
[BUG]: Commmunication with the Streamdeck hardware not working after suspend & resume

### ISSUE THREAD

**Issue by ktuomain** [streamdeck-linux-gui/streamdeck-linux-gui#228]
### In raising this issue I confirm that

- [X] I have fully completed the issue template
- [X] I have searched open and closed issues for duplicates
- [X] I have read the [Contribution Guidelines](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/contributing/contributing-guide/)
- [X] I have read the [Code of Conduct](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/contributing/code-of-conduct/)
- [X] I have read the [Documentation](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/)

### Describe the bug

After resuming from suspend, the display of my Streamdeck device turns on and stays on (even though I have set it to turn off after 10 seconds with the "auto dim after" setting), but pressing the buttons on my Streamdeck doesn't do anything. The interface of the streamdeck-linux-gui seems to respond, but communication with the Streamdeck hardware doesn't seem to work. I have to kill the program using the killall command to get everything working again. However, if I resume very quickly after suspend, I don't seem to have the problem. I don't think this problem was there initially; it appeared after some update a little while ago. I upgraded to Xubuntu 24.04 recently, but I don't remember if the problem started immediately after the upgrading to 24.04 or only a little bit later. 

### Steps to reproduce the behavior

1. Suspend the machine
2. Wait for more than just few minutes
3. Resume
4. Streamdeck-linux-gui is not able to communicate with the hardware anymore

### Expected behavior

I would expect the program to be able to communicate with the Streamdeck hardware even after suspend & resume, without requiring killing of the software & restarting it.

### Screenshots

Going through logs I noticed the following error messages. However, I am not sure if they are related to this problem:

StreamDeck.Transport.Transport.TransportError: No HID device.
    raise TransportError("No HID device.")
  File "/home/username/.local/pipx/venvs/streamdeck-linux-gui/lib/python3.12/site-packages/StreamDeck/Transport/LibUSBHIDAPI.py", line 254, in send_feature_report
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    return self.hidapi.send_feature_report(self.device_handle, payload)
  File "/home/username/.local/pipx/venvs/streamdeck-linux-gui/lib/python3.12/site-packages/StreamDeck/Transport/LibUSBHIDAPI.py", line 399, in write_feature
    self.device.write_feature(payload)
  File "/home/username/.local/pipx/venvs/streamdeck-linux-gui/lib/python3.12/site-packages/StreamDeck/Devices/StreamDeckXL.py", line 106, in set_brightness
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    lambda brightness: self.decks_by_serial[serial_number].set_brightness(brightness),
  File "/home/username/.local/pipx/venvs/streamdeck-linux-gui/lib/python3.12/site-packages/streamdeck_ui/api.py", line 209, in <lambda>
    self.brightness_callback(self.dimmed_brightness())
  File "/home/username/.local/pipx/venvs/streamdeck-linux-gui/lib/python3.12/site-packages/streamdeck_ui/dimmer.py", line 92, in dim
    self.function(*self.args, **self.kwargs)
  File "/usr/lib/python3.12/threading.py", line 1431, in run
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
Traceback (most recent call last):
Exception in thread Thread-11:

### System Information

*Xubuntu 24.04
*Xfce4
*Python	3.12.3

### Stream Deck Version

Stream Deck XL

**Comment by coolapso** [comment]
https://github.com/streamdeck-linux-gui/streamdeck-linux-gui/discussions/203
