### ISSUE TITLE
[BUG]: A Stream Deck is attached, but it could not be opened

### ISSUE THREAD

**Issue by paceyn** [streamdeck-linux-gui/streamdeck-linux-gui#229]
### In raising this issue I confirm that

- [X] I have fully completed the issue template
- [X] I have searched open and closed issues for duplicates
- [X] I have read the [Contribution Guidelines](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/contributing/contributing-guide/)
- [X] I have read the [Code of Conduct](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/contributing/code-of-conduct/)
- [X] I have read the [Documentation](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/)

### Describe the bug

Arch Linux AUR install of `streamdeck-ui` says that a Stream Deck is recognized, but can't connect.

```------------------------
*** Problem detected ***
------------------------
A Stream Deck is attached, but it could not be opened.
Check installation instructions and ensure a udev rule has been added and loaded.
https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/
```

streamdeckc crashes on line 167.

```Traceback (most recent call last):
  File "/usr/bin/streamdeckc", line 8, in <module>
    sys.exit(execute())
             ^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/streamdeck_ui/cli/server.py", line 167, in execute
    sock.connect(path)
FileNotFoundError: [Errno 2] No such file or directory
```

I tried following a similar issue's instructions, but nothing budged. I tried installing `ttf-roboto` through pacman, but it changed nothing, even when I updated my font cache.

### Steps to reproduce the behavior

- `yay -S streamdeck-ui` (read and confirm all dialogues)
- (`yay -S ttf-roboto`)
- `streamdeck`

### Expected behavior

The Stream Deck should be connecting and the interface should be displaying normally.

### System Information

EndeavourOS, KDE 6, Python 3.12.4

### Stream Deck Version

Standard Mk2

**Comment by coolapso** [comment]
Please use streamController instead. https://github.com/streamdeck-linux-gui/streamdeck-linux-gui/discussions/203

**Comment by robbieh** [comment]
@paceyn I ran into this when StreamController was running in the background. Once I found it and closed it, this app worked again. I'm still using this because StreamController just isn't working on my desktop at all.

**Comment by Core447** [comment]
> just isn't working on my desktop at all.

Can you please open an issue on the [StreamController repo](https://github.com/StreamController/StreamController) about this?

**Comment by robbieh** [comment]
> > just isn't working on my desktop at all.
> 
> Can you please open an issue on the [StreamController repo](https://github.com/StreamController/StreamController) about this?

Yes, I already did this.
