### ISSUE TITLE
[BUG]: Write Text missing keystrokes on Firefox

### ISSUE THREAD

**Issue by drsox** [streamdeck-linux-gui/streamdeck-linux-gui#40]
### In raising this issue I confirm that

- [X] I have fully completed the issue template
- [X] I have searched open and closed issues for duplicates
- [X] I have read the [Contribution Guidelines](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/contributing/contributing-guide/)
- [X] I have read the [Code of Conduct](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/contributing/code-of-conduct/)
- [X] I have read the [Documentation](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/)

### Describe the bug

As previously reported on the abandoned project:
https://github.com/timothycrosley/streamdeck-ui/issues/348

Almost every time a write text button is used it misses some key presses from the text when inputting into Firefox. I'm using Pop!_OS and X11.

### Steps to reproduce the behavior

    Configure the following action Write Text on a button with the write text.. 'Gmi Bwgsf - Mdhadnlie.tbd
    I: 06435 241515'

    Press button when on a firefox window with a text input box. (Email, wiki etc.)

    Notice that the stuff it has typed is often missing some letters.

    For example if I press the button 10 times now:

Gmi Bwgsf -Mdhadnlie.tbd
I: 06435 24151
Gmi Bwgsf - Mdhadnlie.tbd
I: 06435 241515
Gmi Bwgsf - Mdhadnlie.tbd
I: 06435 241515
Gmi Bwgsf - Mdhanlie.tbd
I: 06435 241515
Gmi Bwgsf - Mdhadnlie.tbd
I: 06435 241515
Gmi Bwgsf - Mdhadnlie.tbd
I: 06435 24155
Gmi Bwgsf -Mdhadnlie.tbd
I: 06435 24155
Gmi Bwgsf - Mdhanlie.tbd
I: 06435 241515
Gmi Bwgsf - Mdhadnlie.tbd
I: 06435 241515
Gmi Bwgsf - Mdhadnlie.tbd
I: 06435 24151

The problem does not occur when using the button on Text Editor, a console window with VI or a VS Code window.

### Expected behavior

 All keystrokes should be present

### System Information

    OS: Pop!_OS
    Desktop environment: Gnome X11
    Python version Python 3.10.6

### Stream Deck Version

XL

(I'm new to linux and also rarely use GitHub, please excuse anything I've missed out or done wrong!). [Also, thanks for making the streamdeck usable on linux! I use it as a productivity tool rather than gaming or streaming. Having it working on my attempt to switch to linux is a great help!]

**Comment by Data-007** [comment]
I had a script maid for me it works with Discord. Are you using similar or can you use similar.

#!/bin/zsh
wmctrl -xa discord && \
xdotool type 'Good Morning Data'
xdotool key --clearmodifiers Return

HIH @drsox

**Comment by drsox** [comment]
That is stunning and has probably solved my issue. It would be even better if streamdeck-linux-gui could take the "Write Text" input and generate or run the xdotool command on the fly without users having to create scripts themselves.

I suspect the response to this is "you are free to create that and provide the code for inclusion"; sadly it is beyond my ability ;(

**Comment by rkmax** [comment]
@drsox I did some testing by doing the following steps


1. Assign to a button "Write text" the following
```
Gmi Bwgsf - Mdhadnlie.tbd
I: 06435 241515

```

2. Opened some form in the browser (I repet this for chrome and firefox), this is the form URL I used to test https://www.jotform.com/form-templates/responsive-layout-general-inquiry-contact-form

3. Hit the button multiple times while the text area was focused

4. Here is the results
```
Gmi Bwgsf - Mdhadnlie.tbd
I: 06435 241515
Gmi Bwgsf - Mdhadnlie.tbd
I: 06435 241515
Gmi Bwgsf - Mdhadnlie.tbd
I: 06435 241515
Gmi Bwgsf - Mdhadnlie.tbd
I: 06435 241515
Gmi Bwgsf - Mdhadnlie.tbd
I: 06435 241515
Gmi Bwgsf - Mdhadnlie.tbd
I: 06435 241515
Gmi Bwgsf - Mdhadnlie.tbd
I: 06435 241515
Gmi Bwgsf - Mdhadnlie.tbd
I: 06435 241515
Gmi Bwgsf - Mdhadnlie.tbd
I: 06435 241515
Gmi Bwgsf - Mdhadnlie.tbd
I: 06435 241515
Gmi Bwgsf - Mdhadnlie.tbd
I: 06435 241515
Gmi Bwgsf - Mdhadnlie.tbd
I: 06435 241515
Gmi Bwgsf - Mdhadnlie.tbd
I: 06435 241515
Gmi Bwgsf - Mdhadnlie.tbd
I: 06435 241515
Gmi Bwgsf - Mdhadnlie.tbd
I: 06435 241515

```

Here's a recording of that session


https://github.com/streamdeck-linux-gui/streamdeck-linux-gui/assets/395707/043f91c2-0839-42dd-850a-fb9c54787d4e


As you can see no strokes were missing. I'd like tol help to solve the issue. 


streamdeck-linux-gui is using [pynput.keyboard.Controller.type][1] to simulate the writting in the keyboard


I have two hyphotesis of the posible of why this issues is affeting you

First, Something in Pop!_OS is not playing well with [pynput.keyboard.Controller.type][1], this is hard to replicate for me, but we can confirm but giving a try with the solution that @Data-007 mentioned, lets create an script that do exactly that.


Note: I'm assuming your user folder is named `/home/drsox` please update to reflect you actual user folder


1. Create a file `/home/drsox/test-input.sh` with the following content.

```bash
#!/usr/bin/env bash
xdotool type 'Gmi Bwgsf - Mdhadnlie.tbd'
xdotool key --clearmodifiers Return
xdotool type 'I: 06435 241515'
xdotool key --clearmodifiers Return

```

2. Give execution permissions to the script, open a terminal and execute the following commands

```
chmod +x /home/drsox/test-input.sh
```

3. You please ensure that xdotool is installed, open a terminal and execute the following command

```
sudo apt update
sudo apt install xdotool
```


4. Assign the script to the "Command" to a button and test it. If this script works for you. Give me an idea of how I can solve this issue



The second hyphotesis is related to the input, some pages I know this by experience are "heavy" bad designed resulting on have "lag" when your input. if you tested the script that I shared with you you can notice that xdotool actual type slowly, while [pynput.keyboard.Controller.type][1] is very quickly.

Please let me know the results. so I can act accordingly and see if I can solve the problem in the code.





[1]: https://pynput.readthedocs.io/en/latest/keyboard.html#pynput.keyboard.Controller.type

**Comment by drsox** [comment]
xdotool has solved the problem reliably.
I wonder if a custom delay between keystrokes on  pynput.keyboard.Controller.type would solve it too?

My browser is definitely bogged down with many pages and tabs which may also be why I only appear to have the issue in Firefox.. if I had the same amount of stuff open in Chrome it may start suffering the same?

Happy to continue using the xdotool script but it's a bit of a pain having to set it up; once setup it's then zero effort.

**Comment by rkmax** [comment]
thanks for the info @drsox. now I can work on a reliable solution for the app

**Comment by 4s3ti** [comment]
fixed on: https://github.com/streamdeck-linux-gui/streamdeck-linux-gui/releases/tag/v3.2.0
