### ISSUE TITLE
[BUG]: Hotkeys not working

### ISSUE THREAD

**Issue by oparada1988** [streamdeck-linux-gui/streamdeck-linux-gui#49]
### In raising this issue I confirm that

- [X] I have fully completed the issue template
- [X] I have searched open and closed issues for duplicates
- [X] I have read the [Contribution Guidelines](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/contributing/contributing-guide/)
- [X] I have read the [Code of Conduct](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/contributing/code-of-conduct/)
- [X] I have read the [Documentation](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/)

### Describe the bug

Im using OBS and when assigning kotkeys for certain actions Streamdeck UI doesnt seem to make the hotkeys work when OBS is not in focus

Example, i used xev to determine the keypress:

Using keybord OBS behavior works as expected, focus or not.

I check Gnome settings and by default no desktop shortcut are assigned to Ctrl-l+Numpad 1 or4

### Steps to reproduce the behavior

1. set OBS shorcut
2. determine key press using xev
3. assign key in Streamdeck UI

### Expected behavior

pressing key with assign OBS hotkey should work

### Screenshots

![Screenshot from 2023-08-20 06-32-56](https://github.com/streamdeck-linux-gui/streamdeck-linux-gui/assets/4031078/462d5810-268e-47cf-b0ed-d263181c9c01)

### System Information

OS: Ubuntu 22.04.3 LTS
Streamdeck 3.0.1
Gnome 42.9 
Obs 29.1.9
X11

### Stream Deck Version

XL

**Comment by 4s3ti** [comment]
:thinking: I Don't think this is actually a bug .... As far as I know this is the default behavior of OBS and it will only get the shortcuts when on focus. to do what you want I think you need OBS with the websocket plugin. 

however I don't use OBS as much and also I use wayland so can't tell this for sure.

**Comment by oparada1988** [comment]
> 🤔 I Don't think this is actually a bug .... As far as I know this is the default behavior of OBS and it will only get the shortcuts when on focus. to do what you want I think you need OBS with the websocket plugin.
> 
> however I don't use OBS as much and also I use wayland so can't tell this for sure.

Thanks for the reply, sorry about forgetting to assign a title. OBS hotkeys work when out of focus. I tested with the keybord when OBS is out of focus and works as it should. But not on streamdeck. 

I do use the websocket plugin(https://github.com/muesli/obs-cli) but it hasnt been updated for almost 2 years and its missing key features like source volume adjustment. So this was the best workaround I could find :-(

**Comment by 4s3ti** [comment]
Hve you tried with other keys instead of the numpads? might be the case that streamdeck-ui is not sending numpads correctly.

**Comment by oparada1988** [comment]
> Hve you tried with other keys instead of the numpads? might be the case that streamdeck-ui is not sending numpads correctly.
> 
> Try single simple keys first, then simple key combinations,
> 
> might provide some clues

Thanks for the follow up,

SO I went ahead and changed the keybingd to trl+alt+a and z and still does not work when obs is not in focus. Using the keyboard works just fine. I do want to point out that I have Discord toggle mute to ctrl+alt+m and added that to streamdeck which works fine when discord is not in focus.

**Comment by rkmax** [comment]
Just tested #50 and it's working fine
- ![image](https://github.com/streamdeck-linux-gui/streamdeck-linux-gui/assets/395707/958e5c3c-fbcb-41d5-8230-5382d168becc)
- ![image](https://github.com/streamdeck-linux-gui/streamdeck-linux-gui/assets/395707/2678136b-863a-4052-af0f-26c4dce46e2b)

**Comment by oparada1988** [comment]
> Just tested #50 and it's working fine
> 
> * ![image](https://user-images.githubusercontent.com/395707/261871255-958e5c3c-fbcb-41d5-8230-5382d168becc.png)
> * ![image](https://user-images.githubusercontent.com/395707/261871062-2678136b-863a-4052-af0f-26c4dce46e2b.png)

Super awesome! Thank you! Looking forward to the next release :-)
