### ISSUE TITLE
[BUG]: Horizontal misalignment when using non-monospace multiline label

### ISSUE THREAD

**Issue by ajbucci** [streamdeck-linux-gui/streamdeck-linux-gui#64]
### In raising this issue I confirm that

- [X] I have fully completed the issue template
- [X] I have searched open and closed issues for duplicates
- [X] I have read the [Contribution Guidelines](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/contributing/contributing-guide/)
- [X] I have read the [Code of Conduct](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/contributing/code-of-conduct/)
- [X] I have read the [Documentation](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/)

### Describe the bug

Horizontal alignment can be slightly off for multiline text when using a non-monospace label font where both lines share the same # of characters. For example using "hdmi\ntest", "hdmi" is is wider than "test" but "test" is the word being used to calculate the label width since it is the last word in the newline separated string with the greatest # of characters. I have a fix for this already and will submit a pull request but wanted to document the bug here.

### Steps to reproduce the behavior

Use a label with "hdmi\ntest"

### Expected behavior

Should be centered but is slightly off

### System Information

Arch/Gnome

**Comment by 4s3ti** [comment]
Re-opening, not done yet ... on development branch doesn't mean its done :)

**Comment by 4s3ti** [comment]
fixed on: https://github.com/streamdeck-linux-gui/streamdeck-linux-gui/releases/tag/v3.2.0
