### ISSUE TITLE
Could not load the Qt platform plugin "xcb" in "" even though it was found.

### ISSUE THREAD

**Issue by Antony-Lester** [streamdeck-linux-gui/streamdeck-linux-gui#70]
### In raising this issue I confirm that

- [X] I have fully completed the issue template
- [X] I have searched open and closed issues for duplicates
- [X] I have read the [Contribution Guidelines](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/contributing/contributing-guide/)
- [X] I have read the [Code of Conduct](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/contributing/code-of-conduct/)
- [X] I have read the [Documentation](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/)

### Describe the bug

**Might not be project related -- thought i would share
I am not a python guy SO probably barking up a tree ** 

encountered:

> antony@Antonys:~$ streamdeck
> qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
> This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
> 
> Available platform plugins are: wayland, vkkhrdisplay, minimal, offscreen, wayland-egl, linuxfb, minimalegl, xcb, vnc, eglfs.
> 
> Aborted (core dumped)

SOLUTION: 
that appeared to work: 

sudo apt-get install '^libxcb.*-dev' libx11-xcb-dev libglu1-mesa-dev libxrender-dev libxi-dev libxkbcommon-dev libxkbcommon-x11-dev

[https://github.com/NVlabs/instant-ngp/discussions/300#discussioncomment-4169112](url)

### Steps to reproduce the behavior

Launch after fresh install, 

### Expected behavior

UI to launch, 

### System Information

Ubuntu 23*
python 3*

### Stream Deck Version

XL

**Comment by avesgit** [comment]
https://www.avesblog.ru/2023/09/could-not-load-qt-platform-plugin-xcb.html

**Comment by Antony-Lester** [comment]
@avesgit 

`sudo apt-get install '^libxcb.*-dev' libx11-xcb-dev libglu1-mesa-dev libxrender-dev libxi-dev libxkbcommon-dev libxkbcommon-x11-dev`

[source](https://www.avesblog.ru/2023/09/could-not-load-qt-platform-plugin-xcb.html)

this solved the issue, is it possable to bundle this in?
