### ISSUE TITLE
[BUG]: Raspberry Pi Compatibility / PySide6 Alternatives

### ISSUE THREAD

**Issue by ATSiem** [streamdeck-linux-gui/streamdeck-linux-gui#72]
### In raising this issue I confirm that

- [X] I have fully completed the issue template
- [X] I have searched open and closed issues for duplicates
- [X] I have read the [Contribution Guidelines](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/contributing/contributing-guide/)
- [X] I have read the [Code of Conduct](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/contributing/code-of-conduct/)
- [X] I have read the [Documentation](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/)

### Describe the bug

Unable to load on Raspberry Pi without `PySide6`

`pip install PySide6` on Raspberry Pi 4B Ubuntu 22.04 = 

```
ERROR: Could not find a version that satisfies the requirement PySide6 (from versions: none)
ERROR: No matching distribution found for pyside6
```

### Steps to reproduce the behavior

1. Install on Ubuntu via Documentation
2. `streamdeck`
3. `ModuleNotFoundError: No module named 'PySide6'`

### Expected behavior

1. Launch Streamdeck UI

### System Information

Raspberry Pi 4B Ubuntu 22.04

### Stream Deck Version

- Mini
- Additional Mini
- Standard

**Comment by Majiir** [comment]
This is a downstream packaging bug in Ubuntu, not a `streamdeck-linux-gui` issue. I am able to build and run the `aarch64-linux` package of `streamdeck-linux-gui` version `3.0.1` just fine on NixOS.

As a workaround, you can use the Nix package manager on your distro of choice. It's packaged as `streamdeck-ui` in nixpkgs.

**Comment by rkmax** [comment]
perhaps this link help you to build PySide6 for Ubuntu ARM https://gitlab.com/-/snippets/2432339
