### ISSUE TITLE
[BUG]: Can't change horizontal text align

### ISSUE THREAD

**Issue by noeppi-noeppi** [streamdeck-linux-gui/streamdeck-linux-gui#93]
### In raising this issue I confirm that

- [X] I have fully completed the issue template
- [X] I have searched open and closed issues for duplicates
- [X] I have read the [Contribution Guidelines](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/contributing/contributing-guide/)
- [X] I have read the [Code of Conduct](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/contributing/code-of-conduct/)
- [X] I have read the [Documentation](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/)

### Describe the bug

Since commit c6dd6e3065c67852ce9237d53d5596de262d3a7e it is impossible to change the horizontal alignment of button text. This is because the `update_align_text_horizontal` function in `gui.py` calls `api.get_button_text_vertical_align` instead of `api.get_button_text_horizontal_align` (See https://github.com/streamdeck-linux-gui/streamdeck-linux-gui/blob/c6dd6e3065c67852ce9237d53d5596de262d3a7e/streamdeck_ui/gui.py#L771).

### Steps to reproduce the behavior

1. Add some text to a button.
2. Try to change the horizontal alignment.

### Expected behavior

The horizontal alignment should cycle through all three possible values.

### System Information

Isn't important.

**Comment by 4s3ti** [comment]
that's an easy win, Fixed! 

https://github.com/streamdeck-linux-gui/streamdeck-linux-gui/commit/bb09a4f09d6b760c7e11a13425c2e9409683dae1 

Thank you! :)
